# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 45b8f9de3081ed00cad0d26d742e864f289ad28e525bfd046c410fba743aa21a3eef6a5f6a2698bfcd6aa7a4507700b9643cd917684819712acb4e9eb028b2b9

test:
  secret_key_base: 165528a478dbfba2538d7fcbe5692a1daaba5f1d38aeef00570f610e92d2e1c793d9eba5d24d0c41da4e96bb0b4aa3eb6c464107e66c18ad0b7e82b40e6e8481

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
